name: "Debug"
on:
  # curl -fsSL -XPOST \
  #     -H "Accept: application/vnd.github.everest-preview+json" \
  #     -H "Authorization: token $GITHUB_TOKEN" \
  #     --data '{"event_type": "debug"}' \
  #     https://api.github.com/repos/LnL7/nix-darwin/dispatches
  repository_dispatch:
      types:
        - debug
jobs:
  debug:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - run: |
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        nix-channel --update
    - run: |
        nix-shell -A installer
        nix-shell -A installer.check
    - uses: mxschmitt/action-tmate@v2
