name: Update manual
on:
  push:
    branches:
    - master
    paths:
    - '**.nix'

jobs:
  update-manual:
    runs-on: macos-12
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        # So that we fetch all branches, since we need to checkout the `gh-pages` branch later.
        fetch-depth: 0

    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Build manual
      run: |
        nix-build ./release.nix -I nixpkgs=channel:nixpkgs-22.05-darwin -I darwin=. -A manualHTML

    - name: Push update to manual
      run: |
        git checkout gh-pages
        rm -rf manual
        cp -R result/share/doc/darwin manual
        rm result
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git commit -m "Update manual"
        git push
